# Generated by Django 5.2.6 on 2025-10-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='remind_at',
            new_name='reminder_time',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='is_done',
            new_name='seen',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
