# Generated by Django 5.2.9 on 2026-01-05 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='caretaker',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='speech_speed',
            field=models.IntegerField(choices=[(1, 'Slow'), (2, 'Normal')], default=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='support_mode',
            field=models.CharField(choices=[('alz', 'Alzheimer’s / Memory Support'), ('asd', 'Autism Support'), ('adhd', 'ADHD Support'), ('elder', 'Elderly Care'), ('general', 'General Wellness')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='voice_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
