# Generated by Django 5.2.9 on 2026-01-06 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_seen_reminder_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
