# Generated by Django 5.2.9 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reminder_message_alter_reminder_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(),
        ),
    ]
