# Generated by Django 5.2.9 on 2026-01-06 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_reminder_created_at_remove_reminder_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
