# Generated by Django 5.2.9 on 2026-01-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_emergencycontact_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
