# Generated by Django 5.2.9 on 2026-01-08 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_reminder_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='detected_emotion',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='patient',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='emotion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
