# Generated by Django 5.2.9 on 2026-01-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_timestamp_snapshot_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routinetask',
            old_name='description',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='app.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
