# Generated by Django 5.2.9 on 2026-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_description_routinetask_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='user',
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='task',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='time',
            field=models.TimeField(),
        ),
    ]
