# Generated by Django 5.2.9 on 2026-01-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_routine_user_routine_routine_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='routine_type',
        ),
        migrations.AddField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
