# Generated by Django 5.2.9 on 2026-01-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='routinetask',
            old_name='task',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='app.patient'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='icon',
            field=models.CharField(default='⏰', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='time',
            field=models.TimeField(),
        ),
    ]
