# Generated by Django 5.2.9 on 2026-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_emergencycontact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('neutral', 'Neutral'), ('disgust', 'Disgust'), ('Unknown', 'Unknown')], max_length=20)),
                ('image', models.ImageField(upload_to='emotion_snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
