# Generated by Django 5.2.9 on 2026-01-12 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_profile_avatar_remove_profile_dark_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='photo',
            field=models.ImageField(blank=True, default='family_photos/default.jpg', null=True, upload_to='family_photos/'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assistant_image',
            field=models.ImageField(default='assistant_images/default.avif', upload_to='assistant_images/'),
        ),
    ]
