# Generated by Django 5.2.9 on 2026-01-12 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_emergencycontact_photo_alter_emergencycontact_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familycontact',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_photos/'),
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
