# Generated by Django 5.2.9 on 2026-01-12 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_familycontact_created_at_alter_familycontact_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familycontact',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
